export const FETCH_MEMBERS_REQUEST = 'FETCH_MEMBERS_REQUEST';
export const FETCH_MEMBERS_FAILURE = 'FETCH_MEMBERS_FAILURE';
export const FETCH_MEMBERS_SUCCESS = 'FETCH_MEMBERS_SUCCESS';

export const GET_TOTAL_DISTANCE = 'GET_TOTAL_DISTANCE';

export const OPEN_ADD_MEMBER_POPPER = 'OPEN_ADD_MEMBER_POPPER';
export const CLOSE_ADD_MEMBER_POPPER = 'CLOSE_ADD_MEMBER_POPPER';

export const OPEN_ADD_DISTANCE_POPPER = 'OPEN_ADD_DISTANCE_POPPER';
export const CLOSE_ADD_DISTANCE_POPPER = 'CLOSE_ADD_DISTANCE_POPPER';
